### ISSUE TITLE
pacman-panel.sh - replace yaourt with auracle or other helper

### ISSUE THREAD

**Issue by WithThisHerring** [xtonousou/xfce4-panel-generic-monitors#10]
Yaourt has been out of development for a long time.  [Auracle](https://github.com/falconindy/auracle) is a currently developed alternative that will give a list of outdated AUR packages very nicely.

Maybe replace the existing pacman-panel.sh or have variants for different AUR helpers?

Line Dependencies:
replace `yaourt` with `auracle`

Change AUR line to:
`readonly AUR=$(auracle outdated | tee /tmp/aurupdates | wc -l)`

Thank you for this excellent genmon scripts collection.  It is one of the most extensive I've seen!

**Comment by xtonousou** [comment]
Hello @WithThisHerring thanks for your interest!

I added support for `yay`, `auracle` and `yaourt`. You can check it [here](https://github.com/xtonousou/xfce4-genmon-scripts/blob/6d5d34809b5b4757026fbcfed70f0056455c08c8/pacman-panel.sh#L13)

If you find anything cool as an idea, or any misconfiguration please let me know :smile:
