### ISSUE TITLE
How do I remove "Offline" status from spotify-panel.sh script? 

### ISSUE THREAD

**Issue by hujberhunor** [xtonousou/xfce4-panel-generic-monitors#12]
![image](https://user-images.githubusercontent.com/50179148/149148699-603a6c83-41d2-4822-bcbc-011e02aae81b.png)
Should I add some line or remove one? 
I don't know anything about bash scripts.

**Comment by paulmallon** [comment]
You can remove the text by commenting/removing line #52 and #56 in spotify.sh

**Comment by hujberhunor** [comment]
> You can remove the text by commenting/removing line #52 and #56 in spotify.sh

Love you. 
Thanks!

**Comment by xtonousou** [comment]
I've merged this change to main branch. #15
