### ISSUE TITLE
The WINDOW_ID technique didn't work for me

### ISSUE THREAD

**Issue by bonelifer** [xtonousou/xfce4-panel-generic-monitors#13]
The WINDOW_ID technique in spotify-panel.sh didn't work for me. I found this works:
`xdotool search --desktop 0 Spotify windowactivate
`

Nice scripts overall. I managed to add a active icon fairly easy, since your code was concise enough to understand. Now the current icon is the inactive and a green icon is the active.  I've replaced the time/date clock and power management and another genmon(spotify) widget with yours.  Grabbed the click code from the power management script and added it to the datetime script to bring up gworldclock for timezones to replace the python widget that I was using that was buggy.  Really nice work here. Thanks for sharing. Even with the new battery widget I've save some space on my toolbar.

**Comment by xtonousou** [comment]
Thanks @bonelifer !

Do you have the `xdotool` by any chance? This is a required dependency in order to gain focus on windows like Spotify.

**Comment by bonelifer** [comment]
Of course, as you can see my working line starts with "xdotool".

**Comment by xtonousou** [comment]
@bonelifer Could you submit a PR for this please?

**Comment by bonelifer** [comment]
@xtonousou  #16 Done. I assumed you only wanted the xdotool change. If you wanted the inactive/active change, I can push that as well, but I went through 15-20 images before finding the right one, so I can't vouch for the icons licensing as I don't remember where I found it and if I had to make changes to it.
