### ISSUE TITLE
Modified datetime-panel.sh

### ISSUE THREAD

**Issue by bonelifer** [xtonousou/xfce4-panel-generic-monitors#14]
I had modified datetime-panel.sh to an icon only and to invoke gworldclock when clicked and it was working great.  Had to reinstall as OS install had destabilized. Now the ICON has "XXX" text next to it that it didn't have before. Code below:
![datetime-timezone](https://user-images.githubusercontent.com/121736/189257600-ad4c747d-6f57-4e18-a1f6-af2fb9989d50.png)

```
#!/usr/bin/env bash
# Dependencies: bash>=3.2, coreutils, file, gawk, procps-ng

# Makes the script more portable
readonly DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Optional icon to display before the text
# Insert the absolute path of the icon
# Recommended size is 24x24 px
if [ "$(LC_ALL=en_US.UTF-8 date +%d%m)" -eq 1804 ]; then # birthday, 2604 stands for April 26
  readonly ICON="${DIR}/icons/datetime/cake-variant.png"
else
  readonly ICON="${DIR}/icons/calendar/calendar.png"
fi

# Calculate datetime values
readonly TIME=$(LC_ALL=en_US.UTF-8 date +%T)
readonly DATE=$(LC_ALL=en_US.UTF-8 date +%A\ -\ %B\ %d,\ %Y)

# Panel
if [[ $(file -b "${ICON}") =~ PNG|SVG ]]; then
  INFO="<img>${ICON}</img>"
  INFO+="<txt>"
else
  INFO="<txt>"
fi
if hash gworldclock &> /dev/null; then
  INFO+="<click>gworldclock</click>"
fi
INFO+="</txt>"

# Tooltip
MORE_INFO="<tool>"
MORE_INFO+="Click for Timezones"
MORE_INFO+="</tool>"

# Panel Print
echo -e "${INFO}"

# Tooltip Print
echo -e "${MORE_INFO}"
```

**Comment by xtonousou** [comment]
Please refer to the documentation of the [xfce4-genmon-plugin](https://docs.xfce.org/panel-plugins/xfce4-genmon-plugin/start) to get the XML syntax right.

You have to place the `<click>` section outside of the `<txt>` tag. For example:

```bash
#!/bin/bash
echo "<txt>Hello</txt>"
echo "<txtclick>mousepad</txtclick>"
echo "<css>.genmon_valuebutton {background-color:red; color:yellow} .genmon_label {color:green}</css>"
echo "<tool>Hello there</tool>"
```

alternatively to `<txtclick>` there is also the `<click>` and the `<iconclick>`

**Comment by bonelifer** [comment]
Thanks for the help. Strange it was working before I reinstalled. I guess my OS installation was pretty mangled. This advice helped fix the problem.
