### ISSUE TITLE
What user are the commands run under? 

### ISSUE THREAD

**Issue by PublicVoidUpdate** [xtonousou/xfce4-panel-generic-monitors#17]
I'm using genmon on my raspberry pi, to be able to monitor battery, but I'm getting the error that it doesn't think it's on a raspberry pi. My thoughts is that it could be that the user the command is run under doesn't have access to the GPIO because of permissions, but to fix this I would have to give genmon GPIO permission.

TL;DR
To get battery through gpio on rpi i need permissions, and i must know what user runs genmon to give it those permissions.

**Comment by xtonousou** [comment]
Thanks @PublicVoidUpdate for opening an issue!

All the scripts are running with your current user. I suppose, you could create a sudoers.d/genmon file to specify exactly the commands to run with this user. To verify it, you can execute `ps auxf  | grep -i genmon` to check the user.

**Comment by PublicVoidUpdate** [comment]
That's interesting, i kept getting permission issues outputting on Genmon, and after chowning the gpio mem device it complained it wasn't on an RPI when clearly it was lol my guess is that it's an issue with the GPIO python library. Instead i decided to use Gnome and a full custom application because of XFCE having terrible touch screen support.
