### ISSUE TITLE
spotify-panel and spotify.sh  critical error

### ISSUE THREAD

**Issue by samuk190** [xtonousou/xfce4-panel-generic-monitors#8]
![image](https://user-images.githubusercontent.com/19878001/95689613-5c130280-0be8-11eb-9020-033642d15ba1.png)
when I use spotify-panel and spotify.sh at xubuntu with xfce 4
I get tons of bash script process and it doesnt work.
13k process in under 20 seconds!! 
atleast killall bash saved me from restarting (Thx linux)

**Comment by xtonousou** [comment]
Try to update the repo with `git pull`. There was a bug with spotify panel, when a song title had an `&` character the script was forking itself.

It would be nice if you could spot the song's title when things are going wrong. Refer [here](https://github.com/xtonousou/xfce4-genmon-scripts/pull/5).

**Comment by samuk190** [comment]
> Try to update the repo with `git pull`. There was a bug with spotify panel, when a song title had an `&` character the script was forking itself.
> 
> It would be nice if you could spot the song's title when things are going wrong. Refer [here](https://github.com/xtonousou/xfce4-genmon-scripts/pull/5).

thanks. I forked again and it worked spotify-panel.sh
but spotify.sh didnt work? what spotify.sh does? I guess its just the subcomponent right? maybe I was missing it before forking

**Comment by samuk190** [comment]
suggestion: improve script to prevent forking when no "spotify.sh" is found

**Comment by samuk190** [comment]
Opening again, because spotify button doesnt work it doesnt focus, first it said that couldnt locate xdotool, then I installed it, but it didnt work, maybe you can get a clue or use an system package to focus on window spotify?

**Comment by xtonousou** [comment]
Please open another issue with different title that describes you problem.
