### ISSUE TITLE
Cool script: click to show pavucontrol (volume mixer in panel?) [Enhancement]

### ISSUE THREAD

**Issue by samuk190** [xtonousou/xfce4-panel-generic-monitors#9]
I didnt find any volume mixer that works for pulseaudio, eg: pnMixer

I think its possible to create a script to control volume from each application with pavucontrol.

Integrate pavucontrol in a mini window (open/close when click in the script icon)

**Comment by xtonousou** [comment]
The plugin `PulseAudio` does already exists for this kind of task, therefore, extra development for a custom solution (I think) is not a good idea.

**Comment by samuk190** [comment]
> The plugin `PulseAudio` does already exists for this kind of task, therefore, extra development for a custom solution (I think) is not a good idea.

are you sure? because pulseaudio open mixer in separate window everytime I want to change an application volume, kde developed a feature to control app volume in the past..
